services:
  server:
    build:
      context: ./backend
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    profiles:
      - all
 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/scripts/postgres:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    profiles:
      - all
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"