from flask import Flask, request, jsonify, Blueprint
import psycopg2
import logging
from connect import get_db_connection
from services.AlphaVantageService import getCompanyDetailsNonUS, getCompanyDetails

track_blueprint = Blueprint('track', __name__)

# API endpoint to track a company
@track_blueprint.route('/track', methods=['POST'])
def track_company():
    data = request.get_json()

    ticker_code = data.get('ticker_code')
    common_name = data.get('common_name')
    
    if not ticker_code:
        return jsonify({'error': 'Ticker code is required'}), 400
    if not common_name:
        return jsonify({'error': 'Common name is required'}), 400
    
    conn = get_db_connection()

    with conn.cursor() as cur:
        cur = conn.cursor()

        # Check if the company already exists
        cur.execute("SELECT * FROM company WHERE TickerCode = %s", (ticker_code,))
        existing_company = cur.fetchone()

        if existing_company:
            return jsonify({'error': 'Company already tracked'}), 400
        
        

        name = ''
        # get official name
        if "." in ticker_code:
            details = getCompanyDetailsNonUS(ticker_code)
            if not details:
                return jsonify({'error': 'Ticker code does not exist'}), 400
            name = details['name']
        else:
            details = getCompanyDetails(ticker_code)
            if not details:
                return jsonify({'error': 'Ticker code does not exist'}), 400
            name = details['Name']

        # Create a new company
        cur.execute("INSERT INTO company (CompanyName, CommonName, TickerCode) VALUES (%s, %s, %s) RETURNING CompanyID",
                    (name, common_name, ticker_code))
        new_company_id = cur.fetchone()[0]  # Return the company id generated by the insertion

        # Save the company to the tracked companies table
        # This should be modified to be added into the user_follows_company table.
        # cur.execute("INSERT INTO tracked_company (company_id) VALUES (%s)", (new_company_id,))

        # Commit changes
        conn.commit()
        conn.close()
        return jsonify({'message': 'Company successfully tracked'}), 201


