from flask import Flask, request, jsonify, Blueprint
import psycopg2
import logging
from connect import get_db_connection
from services.AlphaVantageService import getCompanyDetailsNonUS, getCompanyDetails

track_blueprint = Blueprint('track', __name__)

# API endpoint to track a company
@track_blueprint.route('/track', methods=['POST'])
def track_company():
    data = request.get_json()

    ticker_code = data.get('ticker_code')
    common_name = data.get('common_name')
    
    if not ticker_code:
        return jsonify({'error': 'Ticker code is required'}), 400
    if not common_name:
        return jsonify({'error': 'Common name is required'}), 400
    
    conn = get_db_connection()

    with conn.cursor() as cur:
        cur = conn.cursor()

        # Check if the company already exists
        cur.execute("SELECT * FROM company WHERE TickerCode = %s", (ticker_code,))
        existing_company = cur.fetchone()

        if existing_company:
            return jsonify({'error': 'Company already tracked'}), 409 #conflict status code
        
        

        name = ''
        exchange = ''
        # get official name and exchange
        if "." in ticker_code:
            details = getCompanyDetailsNonUS(ticker_code)
            if not details:
                return jsonify({'error': 'Ticker code does not exist'}), 400
            name = details['name']
            exchange = details['exchange']
        else:
            details = getCompanyDetails(ticker_code)
            if not details:
                return jsonify({'error': 'Ticker code does not exist'}), 400
            name = details['Name']
            exchange = details['Exchange']

        # Create a new company
        cur.execute("INSERT INTO company (CompanyName, CommonName, TickerCode, Exchange) VALUES (%s, %s, %s, %s) RETURNING CompanyID",
                    (name, common_name, ticker_code, exchange))
        new_company_id = cur.fetchone()[0]  # Return the company id generated by the insertion

        # Save the company to the tracked companies table
        # This should be modified to be added into the user_follows_company table.
        # cur.execute("INSERT INTO tracked_company (company_id) VALUES (%s)", (new_company_id,))
        cur.execute("INSERT INTO user_follows_company (UserID, CompanyID) VALUES (%s, %s)", (1, new_company_id)) 
        # default test userid = 1

        # Commit changes
        conn.commit()
        conn.close()
        return jsonify({'message': f'Company successfully tracked, Common Name = {common_name}, tickerCode= {ticker_code}'}), 201


# API endpoint to return tracked company common names and links
@track_blueprint.route('/trackedCompanies', methods=['GET'])
def tracked_companies():
    conn = get_db_connection()
    with conn.cursor() as cur:
        # Query database to get all tracked company user-created names and ticker codes 
        cur.execute("SELECT c.CommonName, TickerCode FROM user_follows_company ufc JOIN company c ON ufc.CompanyID = c.CompanyID WHERE ufc.UserID = 1;")
        results = cur.fetchall()
    
    conn.close()
    #if rows were found
    tracked_companies = []
    for result in results:
        tracked_companies.append({
            "CommonName": result[0],
            "TickerCode": result[1]
        })
    return jsonify(tracked_companies)


